import type { FieldId } from "@/types";
import type { TaskCard } from "@/types";

// Helper to compute a date offset from today as an ISO string
function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const SEED_TASKS: Record<FieldId, Omit<TaskCard, "id">[]> = {
  freelancer: [
    {
      tag: "Proposal",
      title: "Website redesign pitch — Bloom Café",
      description: "Craft a compelling visual proposal for the café's brand refresh and digital presence.",
      avatars: [],
      comments: 5,
      dueDate: daysFromNow(2),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Outreach",
      title: "Cold email — SaaS onboarding project",
      description: "Write a personalised sequence targeting SaaS founders struggling with activation rates.",
      avatars: [],
      comments: 2,
      dueDate: daysFromNow(5),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Contract",
      title: "Retainer terms — Q4 Lead Gen client",
      description: "Negotiate and finalise monthly retainer scope and deliverables for the new client.",
      avatars: [],
      comments: 8,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Final Delivery",
      title: "Brand style guide — Nomad Coffee Co.",
      description: "Package and deliver the complete brand identity system including tokens and usage rules.",
      avatars: [],
      comments: 3,
      dueDate: daysFromNow(-3),
      status: "scheduled",
      stage: "active",
    },
  ],

  founder: [
    {
      tag: "Strategy",
      title: "Explore B2B pricing model",
      description: "Research competitor pricing tiers and map out a value-metric-based pricing strategy.",
      avatars: [],
      comments: 4,
      dueDate: daysFromNow(3),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Marketing",
      title: "Waitlist landing page copy",
      description: "Write conversion-focused copy for the pre-launch page targeting early adopters.",
      avatars: [],
      comments: 1,
      dueDate: daysFromNow(4),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Product",
      title: "Onboarding flow v1",
      description: "Design and document the user onboarding sequence from signup to first value moment.",
      avatars: [],
      comments: 6,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Product",
      title: "MVP soft launch",
      description: "Co-ordinate the internal soft launch with the core team and first 50 beta users.",
      avatars: [],
      comments: 3,
      dueDate: daysFromNow(-2),
      status: "scheduled",
      stage: "active",
    },
  ],

  student: [
    {
      tag: "Physics",
      title: "Chapter 5 — Thermodynamics",
      description: "Review lecture notes, work through problem sets, and summarise key equations.",
      avatars: [],
      comments: 0,
      dueDate: daysFromNow(2),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "History",
      title: "Essay outline — Modern History",
      description: "Structure the argument for the 2500-word essay on post-war economic recovery.",
      avatars: [],
      comments: 2,
      dueDate: daysFromNow(6),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "CS",
      title: "Group project — Data Structures",
      description: "Implement the binary search tree module and write accompanying unit tests.",
      avatars: [],
      comments: 5,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Chemistry",
      title: "Lab report — Chemistry",
      description: "Write up the titration experiment results and submit through the portal.",
      avatars: [],
      comments: 1,
      dueDate: daysFromNow(-3),
      status: "scheduled",
      stage: "active",
    },
  ],

  hr: [
    {
      tag: "IT Ops",
      title: "New hire laptop request",
      description: "Raise the procurement ticket for the incoming designer's MacBook and peripherals.",
      avatars: [],
      comments: 2,
      dueDate: daysFromNow(2),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Support",
      title: "PTO policy question",
      description: "Clarify the carryover rules for remote employees and update the handbook entry.",
      avatars: [],
      comments: 0,
      dueDate: daysFromNow(4),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Recruiting",
      title: "Background check — Design Candidate",
      description: "Co-ordinate the third-party background verification for the shortlisted design hire.",
      avatars: [],
      comments: 4,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Payroll",
      title: "Payroll discrepancy — Oct cycle",
      description: "Investigate and resolve the overtime miscalculation flagged by the finance team.",
      avatars: [],
      comments: 7,
      dueDate: daysFromNow(-5),
      status: "scheduled",
      stage: "active",
    },
  ],

  marketer: [
    {
      tag: "Content",
      title: "Product launch blog post",
      description: "Explain the revolutionary new feature set for Q4 release with expert insights.",
      avatars: [],
      comments: 6,
      dueDate: daysFromNow(2),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Strategy",
      title: "Q4 video content map",
      description: "Structure the video series for YouTube Shorts and TikTok alignment.",
      avatars: [],
      comments: 3,
      dueDate: daysFromNow(5),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Social",
      title: "LinkedIn Q4 lead gen campaign",
      description: "Finalise the copy for carousel ads targeting CMOs in mid-market SaaS companies.",
      avatars: [],
      comments: 8,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Email",
      title: "Monthly insights newsletter",
      description: "Curate the best blog posts from last month for the subscriber list send.",
      avatars: [],
      comments: 2,
      dueDate: daysFromNow(3),
      status: "scheduled",
      stage: "active",
    },
  ],

  developer: [
    {
      tag: "Bug",
      title: "Fix pagination bug",
      description: "Resolve the off-by-one error causing the last page to show an empty result set.",
      avatars: [],
      comments: 3,
      dueDate: daysFromNow(2),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Feature",
      title: "Add dark mode toggle",
      description: "Implement the system-preference-aware theme switch and persist to localStorage.",
      avatars: [],
      comments: 1,
      dueDate: daysFromNow(5),
      status: "drafting",
      stage: "active",
    },
    {
      tag: "Backend",
      title: "Refactor auth middleware",
      description: "Extract JWT validation into a reusable middleware and add refresh-token support.",
      avatars: [],
      comments: 5,
      dueDate: daysFromNow(1),
      status: "review",
      stage: "active",
    },
    {
      tag: "Backend",
      title: "API rate limiting",
      description: "Implement sliding-window rate limiting on the public endpoints using Redis.",
      avatars: [],
      comments: 2,
      dueDate: daysFromNow(-2),
      status: "scheduled",
      stage: "active",
    },
  ],
};
